# Generated by Django 5.1.6 on 2025-02-06 14:38

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={},
        ),
        migrations.AlterField(
            model_name="cook",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="+", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="cook",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kitchen.dishtype"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
